[package]
name = "esp32-http-temperature"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-hal = "0.43"
esp-idf-svc = "0.50"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

