auto_export: false
auto_import: true
database_path: .arxos/arxos.db
ignore_patterns:
- .*
- ~*
- '*.tmp'
- '*.bak'
max_workers: 4
queue_size: 100
socket_path: /tmp/arxos.sock
state_dir: .arxos
sync_interval: 5m0s
watch_dirs:
- .arxos
watch_patterns:
- '*.pdf'
- '*.ifc'
